University/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using University.Entities;
using University.Models;

namespace University.Controllers
{
    
    public class SuperAdminController : Controller
    {
      
        // Object of Context class is made.
        private UserContext db = new UserContext();

        public ActionResult Index(string searching)
        {
            var users = from s in db.Users select s;
            if (!String.IsNullOrEmpty(searching))
            {
                users = users.Where(s => s.Role.RoleName.Contains(searching) && s.RoleId != 1 && s.RoleId != 2 || s.FirstName.Contains(searching) ||
                 s.LastName.Contains(searching) || s.course.CourseName.Contains(searching));

            }
            return View(users.ToList());
        }

        /// <summary>
        /// To show List of all Users and Admin
        /// </summary>
        /// <returns></returns>
        public ActionResult GetAllUsers(string searching)
        {
            if(Session["UserId"]==null && Session["UserName"] == null)
            {
                return RedirectToAction("Login","UserView");
            }

            var users = from s in db.Users where s.RoleId !=1 select s;
            if (!String.IsNullOrEmpty(searching))
            {
                users = users.Where(s => s.Role.RoleName.Contains(searching) && s.RoleId != 1);

            }
           
            return View(users.OrderBy(s=>s.FirstName).ToList());
        }


        /// <summary>
        ///  GET: To Show the details of the Students
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult UserDetails(int id)
        {
            if (Session["UserId"] == null && Session["UserName"] == null)
            {
                return RedirectToAction("Login", "UserView");
            }
            // Code to show Roles in DropDown
            List<Role> objRoleList = GetRoles();
            ViewBag.Role = objRoleList;
            // Code to show Courses in DropDown
            List<Course> objCourseList = db.Courses.Where(x => x.IsActive == true).ToList();
            ViewBag.Course = objCourseList;
            // Code to show Countries in DropDown
            List<Country> countryList = db.Country.ToList();
            ViewBag.CountryList = new SelectList(countryList, "CountryId", "Name");
            //Code to Show State Dropdown
            List<State> statesList = db.States.ToList();
            ViewBag.StateList = new SelectList(statesList, "StateId", "Name");
            //Code to show City dropDown
            List<City> citiesList = db.City.ToList();
            ViewBag.CityList = new SelectList(citiesList, "CityId", "Name");

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            User objUser = db.Users.Find(id);

            UserViewModel objUserViewModel = new UserViewModel();
            objUserViewModel.FirstName = objUser.FirstName;
            objUserViewModel.LastName = objUser.LastName;
            objUserViewModel.Gender = objUser.Gender;
            objUserViewModel.Hobbies = objUser.Hobbies;
            objUserViewModel.Email = objUser.Email;
            objUserViewModel.Password = objUser.Password;
            objUserViewModel.ConfirmPassword = objUser.ConfirmPassword;
            objUserViewModel.DateOfBirth = objUser.DateOfBirth;
            objUserViewModel.RoleId = objUser.RoleId;
            objUserViewModel.CourseId = objUser.CourseId;
            objUserViewModel.IsActive = objUser.IsActive;
            objUserViewModel.DateCreated = objUser.DateCreated;
            objUserViewModel.DateModified = objUser.DateModified;
            objUserViewModel.AddressLine1 = objUser.Address.AddressLine1;
            objUserViewModel.AddressLine2 = objUser.Address.AddressLine2;
            objUserViewModel.CountryId = objUser.Address.CountryId;
            objUserViewModel.StateId = objUser.Address.StateId;
            objUserViewModel.CityId = objUser.Address.CityId;
            objUserViewModel.ZipCode = objUser.Address.ZipCode;

            if (objUser == null)
            {
                return HttpNotFound();
            }
            return View(objUserViewModel);
        }
        /// <summary>
        /// GET To Create new User Record
        /// </summary>
        /// <returns></returns>

        public ActionResult CreateUser()
        {
            if (Session["UserId"] == null && Session["UserName"] == null)
            {
                return RedirectToAction("Login", "UserView");
            }
            // Code to show DropDown for Role.
            List<Role> roleList = GetRoles();
            ViewBag.RoleList = new SelectList(roleList, "RoleId", "RoleName");
            // Code to show DropDown for Course.
            List<Course> courseList = db.Courses.Where(x => x.IsActive == true).ToList();
            ViewBag.CourseList = new SelectList(courseList, "CourseId", "CourseName");
            //Code to show DropDown for Country.
            List<Country> countryList = db.Country.ToList();
            ViewBag.CountryList = new SelectList(countryList, "CountryId", "Name");


            return View();
        }
        /// <summary>
        /// Post method : To Create new user Record
        /// </summary>
        /// <param name="objUserModel"></param>
        /// <returns></returns>

        [HttpPost]
        public ActionResult CreateUser(UserViewModel objUserModel)
        {
            if (Session["UserId"] == null && Session["UserName"] == null)
            {
                return RedirectToAction("Login", "UserView");
            }
            // Code to show Roles in DropDown
            List<Role> roleList = GetRoles();
            ViewBag.RoleList = new SelectList(roleList, "RoleId", "RoleName");
            // Code to show Courses in DropDown
            List<Course> courseList = db.Courses.Where(x => x.IsActive == true).ToList();
            ViewBag.CourseList = new SelectList(courseList, "CourseId", "CourseName");
            // Code to show Countries in DropDown
            List<Country> countryList = db.Country.ToList();
            ViewBag.CountryList = new SelectList(countryList, "CountryId", "Name");

            //objUserModel.UserId = 1;
            //objUserModel.AddressId = 1;

            /* Create the TransactionScope to execute the commands, guaranteeing
              
             that both commands can commit or roll back as a single unit of work.*/
            
            using (var transaction = db.Database.BeginTransaction())
            {

                try
                {
                    Address address = new Address
                    {

                        //address.AddressId = objUserModel.AddressId;
                        AddressLine1 = objUserModel.AddressLine1,
                        AddressLine2 = objUserModel.AddressLine2,
                        CountryId = objUserModel.CountryId,
                        StateId = objUserModel.StateId,
                        CityId = objUserModel.CityId,
                        ZipCode = objUserModel.ZipCode
                    };

                    db.Addresses.Add(address); //Address of the user is stored in the DataBase.
                    db.SaveChanges();

                    //Data is saved in the User Table.
                    int latestAddressId = address.AddressId;

                    User obj = new User
                    {
                        FirstName = objUserModel.FirstName,
                        LastName = objUserModel.LastName,
                        Gender = objUserModel.Gender,
                        Hobbies = objUserModel.Hobbies,
                        Password = objUserModel.Password,
                        ConfirmPassword = objUserModel.ConfirmPassword,
                        IsVerified = objUserModel.IsVerified,
                        Email = objUserModel.Email,
                        DateOfBirth = objUserModel.DateOfBirth,
                        IsActive = true,
                        DateCreated = DateTime.Now,
                        DateModified = DateTime.Now,
                        RoleId = objUserModel.RoleId,
                        CourseId = objUserModel.CourseId,
                        AddressId = latestAddressId
                    };
                    db.Users.Add(obj);      
                    db.SaveChanges();

                    // User and their Roles are saved in the UserInRole Table.
                    int latestUserId = obj.UserId;
                    UserInRole userInRole = new UserInRole
                    {
                        RoleId = objUserModel.RoleId,
                        UserId = latestUserId
                    };
                    db.UserInRoles.Add(userInRole);

                    db.SaveChanges();
                    transaction.Commit();
                    return RedirectToAction("GetAllUsers");
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ModelState.AddModelError(string.Empty, ex.Message);
                    throw ex;
                }

            }

        }
        /// <summary>
        ///  GET: To Edit User Record
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult EditUser(int id)
        {
            if (Session["UserId"] == null && Session["UserName"] == null)
            {
                return RedirectToAction("Login", "UserView");
            }
            // Code to show Roles in DropDown
            List<Role> objRoleList = GetRoles();
            ViewBag.Role = objRoleList;
            // Code to show Courses in DropDown

University/Views/SuperAdmin/Create.cshtml
@model University.Models.UserViewModel

@{
    ViewBag.Title = "CreateUser";
}


<script src="~/Scripts/jquery-1.7.1.min.js"></script>

<script>

    $(document).ready(function () {

        $("#country").change(function () {
            var id = $(this).val();
            alert(id);
            $("#state").empty();
            $.getJSON("StateBind",{countryId: id },function(data)
            {

                var v = "<option>..Select State..</option>";
                $.each(data, function (i, v1)
                {
                    v += "<option Value=" + v1.Value + ">" + v1.Text + "</option>";

                });
                $("#state").html(v);
            });
        });

        $("#state").change(function () {

            var id = $(this).val();
            $("#city").empty();
            $.getJSON("CityBind", { stateId: id }, function (data) {

                var v = "<option>..Select City..</option>";
                $.each(data, function (i, v1) {
                    v += "<option Value=" + v1.Value + ">" + v1.Text + "</option>";

                });
                $("#city").html(v);
            });
        });

    });
</script>


<h2>CreateUser</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                Male  @Html.RadioButton("Gender", "Male")

                Female  @Html.RadioButton("Gender", "Female")
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsVerified, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsVerified)
                    @Html.ValidationMessageFor(model => model.IsVerified, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Hobbies, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Hobbies, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Hobbies, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.HiddenFor(model => model.AddressId, htmlAttributes: new { @class = "control-label col-md-2" })
           
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, "Temporary Address",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2,"PermanantAddress", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CountryId,"Country", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", ViewBag.CountryList as SelectList, "--select--", htmlAttributes: new { id = "country", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="state" name="StateId">...Select..</select>
            </div>
        </div>
       

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, "City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select id="city" name="CityId">...Select..</select>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RoleId, "Role", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RoleId", ViewBag.RoleList as SelectList, "..select..", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "Course", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", ViewBag.CourseList as SelectList, "..select..", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
                </div>
            </div>*@

        @*<div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

    <div>
        @Html.Partial("BackToListButtonPartial")
    </div>

University/Views/SuperAdmin/Delete.cshtml
@model University.Models.UserViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVerified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVerified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Hobbies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Hobbies)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.AddressId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressId)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddressLine2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressLine2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CountryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CountryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StateId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StateId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CourseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ZipCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        @Html.Partial("BackToListButtonPartial")
    </div>
    }
</div>

University/Views/SuperAdmin/GetAllUsers.cshtml
@model IEnumerable<University.Entities.User>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";

}
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

@if (Session["UserId"] != null)
{
    <h4>Hello @Session["UserName"].ToString()</h4>
}




<style>
    .table {
        margin-top: 15px;
    }

    th, td {
        border: 1px solid #333;
        padding: 5px;
        vertical-align: middle;
    }

    label {
        margin-right: 10px;
    }
    .table-responsive {
       
        border: 1px solid #333;
    }
</style>
<h3>Users List</h3>
<p>
    @Html.Partial("CreateButtonPartial")
</p>
@using (Html.BeginForm("GetAllUsers", "SuperAdmin", FormMethod.Get))
{
    @Html.Label("Search")
    @Html.TextBox("searching")
    <input type="submit" value="submit" />
}
    <div class="table-responsive">

        <table class="table table-striped">
            <tr class="success">


                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Gender)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsVerified)
                </th>
                @* <th>
                    @Html.DisplayNameFor(model => model.Password)
                </th>
                <th>
                        @Html.DisplayNameFor(model => model.AddressId)
                    </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.Address.AddressLine1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.AddressLine2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.Country.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.State.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.City.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Address.ZipCode)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.Hobbies)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.course.CourseName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Role.RoleName)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.ConfirmPassword)
                </th>*@

                <th>
                    @Html.DisplayNameFor(model => model.IsActive)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateModified)
                </th>*@
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Gender)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateOfBirth)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsVerified)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>*@
                    @*<td>
                        @Html.DisplayFor(modelItem => item.AddressId)
                    </td>*@


                    <td>
                        @Html.DisplayFor(modelItem => item.Address.AddressLine1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address.AddressLine2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address.Country.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address.State.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address.City.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address.ZipCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hobbies)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.course.CourseName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role.RoleName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsActive)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.DateCreated)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateModified)
                    </td>*@
                    <td>
                        @Html.ActionLink("Edit", "EditUser", new { id = item.UserId }) |
                        @Html.ActionLink("Details", "UserDetails", new { id = item.UserId }) |
                        @Html.ActionLink("Delete", "DeleteUser", new { id = item.UserId })
                    </td>
                </tr>
            }

        </table>
    </div>