University/Controllers/UserViewController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using University.Entities;
using University.Models;

namespace University.Controllers
{
    public class UserViewController : Controller
    {
        // Object of Context class is made.

        UserContext db = new UserContext();

        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// GET Method: For Creating User
        /// </summary>
        /// <returns></returns>
        public ActionResult UserRegistration()
        {
            //UserViewModel objUserViewModel = new UserViewModel();
            //var queryRole = (from role in db.Roles select role).ToList();

            //objUserViewModel.RoleList = queryRole;

            //Code to show DropDown of Role
            List<Role> roleList = GetRoles();
            ViewBag.RoleList = new SelectList(roleList, "RoleId", "RoleName");
            //Code to show Dropdown of Cousre
            List<Course> courseList = db.Courses.Where(x=>x.IsActive==true).ToList();
            ViewBag.CourseList = new SelectList(courseList, "CourseId", "CourseName");
            // Code to show DropDown of Country
            List<Country> countryList = db.Country.ToList();
            ViewBag.CountryList = new SelectList(countryList, "CountryId", "Name");

            return View();
        }
        /// <summary>
        /// Post Method: To Post the data of User in User table.
        /// </summary>
        /// <param name="objUserModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UserRegistration(UserViewModel objUserModel)
        {
            //Code to show DropDown of Role
            List<Role> roleList = GetRoles();
            ViewBag.RoleList = new SelectList(roleList, "RoleId", "RoleName");
            //Code to show Dropdown of Cousre
            List<Course> courseList = db.Courses.Where(x => x.IsActive == true).ToList();
            ViewBag.CourseList = new SelectList(courseList, "CourseId", "CourseName");
            // Code to show DropDown of Country
            List<Country> countryList = db.Country.ToList();
            ViewBag.CountryList = new SelectList(countryList, "CountryId", "Name");
         
            // Create the TransactionScope to execute the commands, guaranteeing
            // that both commands can commit or roll back as a single unit of work.

            using (var transaction = db.Database.BeginTransaction())
            {

                try
                {
                    if (ModelState.IsValid)
                    {
                        //Address of the user is stored in the DataBase.
                        Address address = new Address();

                        //address.AddressId = objUserModel.AddressId;
                        address.AddressLine1 = objUserModel.AddressLine1;
                        address.AddressLine2 = objUserModel.AddressLine2;
                        address.CountryId = objUserModel.CountryId;
                        address.StateId = objUserModel.StateId;
                        address.CityId = objUserModel.CityId;
                        address.ZipCode = objUserModel.ZipCode;
                        db.Addresses.Add(address);
                        db.SaveChanges();

                        //Data is saved in the User Table.
                        User objUser = new User();
                        int latestAddressId = address.AddressId;
                        //obj.UserId = objUserModel.UserId;
                        objUser.FirstName = objUserModel.FirstName;
                        objUser.LastName = objUserModel.LastName;
                        objUser.Gender = objUserModel.Gender;
                        objUser.Hobbies = objUserModel.Hobbies;
                        objUser.Password = objUserModel.Password;
                        objUser.ConfirmPassword = objUserModel.ConfirmPassword;
                        objUser.IsVerified = objUserModel.IsVerified;
                        objUser.Email = objUserModel.Email;
                        objUser.DateOfBirth = objUserModel.DateOfBirth;
                        objUser.IsActive = objUserModel.IsActive;
                        objUser.DateCreated = DateTime.Now;
                        objUser.DateModified = DateTime.Now;
                        objUser.RoleId = objUserModel.RoleId;
                        objUser.CourseId = objUserModel.CourseId;
                        objUser.AddressId = latestAddressId;

                        db.Users.Add(objUser);
                        db.SaveChanges();

                        // User and their Roles are saved in the UserInRole Table.
                        int latestUserId = objUser.UserId;
                        UserInRole userInRole = new UserInRole();
                        userInRole.RoleId = objUserModel.RoleId;
                        userInRole.UserId = latestUserId;

                        db.UserInRoles.Add(userInRole);
                        db.SaveChanges();

                        transaction.Commit();
                        return RedirectToAction("Login");
                    }

                    return View(objUserModel);
                }

                catch (Exception ex)
                {
                    transaction.Rollback();
                    ViewBag.ResultMessage = "Error occurred in the registration process.Please register again.";
                    throw ex;
                }

            }
        }

        /// <summary>
        /// GET Method: For User Login
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            return View();
        }
        /// <summary>
        /// Post Method: To Authenticate User Identity
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {

           
            var userDetails = db.Users.Where(x => x.Email == user.Email && x.Password == user.Password ).FirstOrDefault();

           
            //Code to Authenticate Identity Of user.

            if (userDetails != null && userDetails.IsActive == true && userDetails.IsVerified==true)
            {

                Session["RoleId"] = userDetails.RoleId.ToString();
                Session["UserId"] = userDetails.UserId.ToString();
                Session["UserName"] = userDetails.Email.ToString();
                //For SuperAdmin
                if (userDetails.RoleId == 1)
                {
                    Session["RoleId"] = 1;
                    return RedirectToAction("GetAllUsers", "SuperAdmin");
                }
                //For Admin
                else if (userDetails.RoleId == 2)
                {
                    Session["RoleId"] = 2;
                    // return RedirectToAction("GetAllUsers", "Admin");
                    return RedirectToAction("GetAllUsers", "Admin", new { area = "Admin" });
                }
                //For Teacher
                else if (userDetails.RoleId == 3)
                {
                    Session["User"] = userDetails;

                    return RedirectToAction("MyProfile", "Teachers");
                }
                //For Student
                else if (userDetails.RoleId == 4)
                {
                    Session["User"] = userDetails;

                    return RedirectToAction("MyProfile", "Student");
                }
            }
           
            else if (userDetails == null)
            {
                ModelState.AddModelError("", "UserName or Password is wrong");

            }
           
            else if (userDetails.IsVerified != true)
            {
                ModelState.AddModelError("", "Please Verify Your Email By Admin");
            }
            else if (userDetails.IsActive != true)
            {
                ModelState.AddModelError("", "Your Account has not been Activated By Admin");
            }
            return View();
        }
        //To display ThankYou page after Registration.
        public ActionResult ThankYou()
        {
            return View();
        }

        /// <summary>
        /// Action method for LogOut
        /// </summary>
        /// <returns></returns>
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();
            Session.RemoveAll();
            Session.Remove("UserId");
            Session.Remove("UserName");
            Session.Remove("User");

            ////back button 
            //Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            //Response.Cache.SetCacheability(HttpCacheability.NoCache);
            //Response.Cache.SetNoStore();

            //return RedirectToAction("ThankYou");
            //    if (Session["UserId"] !=null && Session["UserName"] == null)
            //{
            //    Session.Abandon();
            //    Session.RemoveAll();
            //    Session.Remove("UserId");
            //    return RedirectToAction("Login");
            //}
            //else
            //{

            //    return RedirectToAction("Login");

            //}
            Response.AddHeader("Cache-Control", "no-cache, no-store,must-revalidate");
            Response.AddHeader("Pragma", "no-cache");
            Response.AddHeader("Expires", "0");
            Session.Abandon();
            Session.Clear();
            Session.RemoveAll();
            Session["UserId"] = null;
            Session["UserName"] = null;
            Session["User"] = null;
          
            return RedirectToAction("Login");
        }

        // Get All Roles

University/Views/Shared/BackTolistButtonPartial.cshtml
<a type="button" class="btn btn-primary btn-sm"
   href="@Url.Action("GetAllUsers")">
    <span class="glyphicon glyphicon-list"></span>
    <span>Back to list</span>
</a>

University/Views/Shared/CreateButtonPartial.cshtml
<a type="button" class="btn btn-primary btn-sm"
   href="@Url.Action("CreateUser")">
    <span class="glyphicon glyphicon-plus"></span>
    <span>Create new</span>
</a>

University/Views/Shared/_AdminMenuPartial.cshtml
@if (Convert.ToInt32(Session["RoleId"]) == 2)
{

    <li Class="DropDown" data-admin-menu>
        <a href="#">
            Admin
            <span class="glyphicon glyphicon-chevron-down"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li class="dropdown-header">Minor Entities</li>
            <li class="divider" />
            <li><a href="/University/Admin/Admin/GetAllUsers">&nbsp;&nbsp;UserList</a></li>
            <li><a href="/University/Admin/Course">&nbsp;&nbsp;Course</a></li>
            <li><a href="/University/Admin/Subject">&nbsp;&nbsp;Subject</a></li>
            <li><a href="/University/Admin/SubjectInCourse">&nbsp;&nbsp;SubjectInCourse</a></li>
            <li><a href="/University/Admin/TeacherInSubject">&nbsp;&nbsp;TeacherInSubject</a></li>







        </ul>

    </li>
}
else if (Convert.ToInt32(Session["RoleId"]) == 1)
{

<li Class="DropDown" data-admin-menu>
    <a href="#">
        Admin
        <span class="glyphicon glyphicon-chevron-down"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
        <li class="dropdown-header">Minor Entities</li>
        <li class="divider" />
        <li><a href="/University/SuperAdmin/GetAllUsers">&nbsp;&nbsp;UserList</a></li>
        <li><a href="/University/Admin/Course">&nbsp;&nbsp;Course</a></li>
        <li><a href="/University/Admin/Subject">&nbsp;&nbsp;Subject</a></li>
        <li><a href="/University/Admin/SubjectInCourse">&nbsp;&nbsp;SubjectInCourse</a></li>
        <li><a href="/University/Admin/TeacherInSubject">&nbsp;&nbsp;TeacherInSubject</a></li>







    </ul>

</li>

}

University/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

University/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

University/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style type="text/css">
        .navbar-header img{
            padding-top:5px;
            width:150px;
        }
        .navbar-brand {
            font-size: 25px;
           
        }
        body {
            background-image: /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#cedce7+0,596a72+100;Grey+3D+%231 */
            background: rgb(206,220,231); /* Old browsers */
            background: -moz-linear-gradient(-45deg, rgba(206,220,231,1) 0%, rgba(89,106,114,1) 100%); /* FF3.6-15 */
            background: -webkit-linear-gradient(-45deg, rgba(206,220,231,1) 0%,rgba(89,106,114,1) 100%); /* Chrome10-25,Safari5.1-6 */
            background: linear-gradient(135deg, rgba(206,220,231,1) 0%,rgba(89,106,114,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#cedce7', endColorstr='#596a72',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=""><img src="http://www.amity.edu/images/logo.png" /></a>
                @*@Html.ActionLink("Amity University", "Login", "UserView", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            @*<div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @Html.Partial("_AdminMenuPartial")
                </ul>
               *<ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Register", "UserRegistration", "UserView", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("Log in", "Login", "UserView", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>
            </div>*@
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
       
      
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AMITY University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Admin")
    @RenderSection("scripts", required: false)
</body>
</html>

University/Views/Shared/_MyLayoutPage.cshtml
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-header img {
            padding-top: 5px;
            width: 150px;
        }
        .navbar-brand {
            font-size: 25px;
        }
        body {
            background-image: /* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#f2f5f6+0,e3eaed+37,c8d7dc+100;Grey+3D+%234 */
            background: rgb(242,245,246); /* Old browsers */
            background: -moz-linear-gradient(-45deg, rgba(242,245,246,1) 0%, rgba(227,234,237,1) 37%, rgba(200,215,220,1) 100%); /* FF3.6-15 */
            background: -webkit-linear-gradient(-45deg, rgba(242,245,246,1) 0%,rgba(227,234,237,1) 37%,rgba(200,215,220,1) 100%); /* Chrome10-25,Safari5.1-6 */
            background: linear-gradient(135deg, rgba(242,245,246,1) 0%,rgba(227,234,237,1) 37%,rgba(200,215,220,1) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
            filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#f2f5f6', endColorstr='#c8d7dc',GradientType=1 ); /* IE6-9 fallback on horizontal gradient */
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href=""><img src="http://www.amity.edu/images/logo.png" /></a>
                @*@Html.ActionLink("Amity University", "Login", "UserView", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li>@Html.ActionLink("Logout", "LogOut", "UserView", routeValues: null, htmlAttributes: new { @class = "navbar-brand",id = "loginLink" })</li>

            </ul>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*@Html.Partial("_AdminMenuPartial")*@
                </ul>
            </div>



        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AMITY University</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Admin")
    @RenderSection("scripts", required: false)
</body>
</html>